In [10]:
%pip install pydotplus
%pip install scikit-learn

Requirement already satisfied: pydotplus in c:\users\nasla\anaconda3\lib\site-packages (2.0.2)
Requirement already satisfied: pyparsing>=2.0.1 in c:\users\nasla\anaconda3\lib\site-packages (from pydotplus) (3.0.4)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: scikit-learn in c:\users\nasla\anaconda3\lib\site-packages (1.0.2)
Requirement already satisfied: joblib>=0.11 in c:\users\nasla\anaconda3\lib\site-packages (from scikit-learn) (1.1.0)
Requirement already satisfied: numpy>=1.14.6 in c:\users\nasla\anaconda3\lib\site-packages (from scikit-learn) (1.21.5)
Requirement already satisfied: scipy>=1.1.0 in c:\users\nasla\anaconda3\lib\site-packages (from scikit-learn) (1.7.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\nasla\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
#importing libraries
import pandas as pd
import sklearn
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

import pydotplus

from IPython.display import Image

In [2]:
dataset= pd.read_csv('golf.csv')

In [3]:
dataset.head(3)

   Unnamed: 0   Outlook Temperature Humidity  Windy Play
0           0     sunny         hot     high  False   no
1           1     sunny         hot     high   True   no
2           2  overcast         hot     high  False  yes

In [4]:
dataset

    Unnamed: 0   Outlook Temperature Humidity  Windy Play
0            0     sunny         hot     high  False   no
1            1     sunny         hot     high   True   no
2            2  overcast         hot     high  False  yes
3            3     rainy        mild     high  False  yes
4            4     rainy        cool   normal  False  yes
5            5     rainy        cool   normal   True   no
6            6  overcast        cool   normal   True  yes
7            7     sunny        mild     high  False   no
8            8     sunny        cool   normal  False  yes
9            9     rainy        mild   normal  False  yes
10          10     sunny        mild   normal   True  yes
11          11  overcast        mild     high   True  yes
12          12  overcast         hot   normal  False  yes
13          13     rainy        mild     high   True   no

In [5]:
#one hot encoding
x=pd.get_dummies(dataset[['Outlook','Temperature','Humidity','Windy']])

In [6]:
x

,Windy,Outlook_overcast,Outlook_rainy,Outlook_sunny,Temperature_cool,Temperature_hot,Temperature_mild,Humidity_high,Humidity_normal
0,False,0,0,1,0,1,0,1,0
1,True,0,0,1,0,1,0,1,0
2,False,1,0,0,0,1,0,1,0
3,False,0,1,0,0,0,1,1,0
4,False,0,1,0,1,0,0,0,1
5,True,0,1,0,1,0,0,0,1
6,True,1,0,0,1,0,0,0,1
7,False,0,0,1,0,0,1,1,0
8,False,0,0,1,1,0,0,0,1
9,False,0,1,0,0,0,1,0,1
10,True,0,0,1,0,0,1,0,1
11,True,1,0,0,0,0,1,1,0
12,False,1,0,0,0,1,0,0,1
13,True,0,1,0,0,0,1,1,0

In [7]:
y=dataset['Play']

In [8]:
y

0      no
1      no
2     yes
3     yes
4     yes
5      no
6     yes
7      no
8     yes
9     yes
10    yes
11    yes
12    yes
13     no
Name: Play, dtype: object

In [9]:
#decision tree model
model = tree.DecisionTreeClassifier(
    criterion = 'entropy', random_state=100 # address ko lagi use garinxa randome_state
)

In [10]:
model.fit(x,y)

DecisionTreeClassifier(criterion='entropy', random_state=100)

In [11]:
data_plot = tree.export_graphviz(model, out_file=None, feature_names = list(x.columns.values), class_names=['Not_play', 'Play'], 
                                 rounded=True, filled=True)
graph = pydotplus.graph_from_dot_data(data_plot)

Image(graph.create_png())

InvocationException: GraphViz's executables not found